# Generated by Django 3.2.9 on 2021-11-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['date_added']},
        ),
    ]
