# Generated by Django 3.2.9 on 2021-11-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursereview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-date_added']},
        ),
    ]
